### PR TITLE
fix: RU to iso codes

### PR DESCRIPTION
**Pull request by qgolsteyn**
This PR moves the RU scraper to use ISO codes. It also aggregates all data to the country level, which was not done previously.

@hyperknot: We are missing population data for Sevastopol, other than that it looks good!

### CODE REVIEW

**Comment by qgolsteyn** [comment]
image

**Comment by qgolsteyn** [comment]
Google Translate was my friend! Manually went through each one of them, I double-checked the mapping!

**Comment by hyperknot** [comment]
Wow, this is rad! Thanks for putting in the effort to do this one!

**Comment by hyperknot** [comment]
I've added missing populations.

**Pull request merged**
