### PR TITLE
Updated the population data for some of the missing states in India

### PR DESCRIPTION
**Pull request by pankaj-giri**
## Summary

#687

Some of the states were missing in the json.

Added the missing states in the json

### CODE REVIEW

**Comment by hyperknot** [comment]
Thanks for doing this, however we are migrating away from using this json file. Can you check if the population information is correct on this page?
https://github.com/hyperknot/country-levels/blob/master/docs/iso2_list/IN.md

**Comment by pankaj-giri** [comment]
It looks very different from - 
https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_population
The JSON file earlier was referring to this link too.

**Comment by hyperknot** [comment]
Can you point to one row which is very different? If it's only about not-the-most-recent census count, then we should update the Wikidata values.

**Comment by pankaj-giri** [comment]
If you take a look at the first entry 
Andaman and Nicobar Islands - wikipedia link lists the population as 380,520 whereas IN.md lists it as 356,152.
Andra Pradesh - wikipedia - 49,386,799, IN.md - 84,580,777. Thats quite a variance.
Looks like what you're picking from wikidata is very dated - 2005

**Comment by pankaj-giri** [comment]
https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_population
You can use this one which is from the 2011 census

**Comment by pankaj-giri** [comment]
Non related to this problem - we have the scrapers run at the individual level broken I think.. Eg.
yarn start --location "IND" or "IN" does not work. This was working yesterday. Same is the case with 
yarn start --location "ITA" or "IT"

**Comment by hyperknot** [comment]
@pankaj-giri that Andaman and Nicobar Islands  is just old data. 
Andra Pradesh on the other hand is very complicated and I'm chatting with Wikidata people about it.

**Comment by hyperknot** [comment]
@pankaj-giri I'm working on fixing the state scrapers.

**Comment by lazd** [comment]
@pankaj-giri run `yarn start -l "iso1:IN"`

**Pull request closed without merging**
