### PR TITLE
ArcGIS pagination

### PR DESCRIPTION
**Pull request by shaperilio**
This pull request is to replace #835; I'm trying to address @jzohrab's comment about not updating the cache submodule, but to be honest, I can't see when it was done, or how to undo it.

This would address #832.

All scrapers were migrated and eye-tested.

I've defined a transition date so that we don't get cache misses when building timeseries. In this PR the date's been changed:

```
const ARCGIS_PAGINATION_DEPLOY_DATE = '2020-04-25'
```

Please take a look if you haven't already looked at the old one. (Nothing's changed here other than bringing it up to date with master and changing the deploy date.

### CODE REVIEW

**Comment by jzohrab** [comment]
Hi @shaperilio , my cache review was for this change:

image

You can (should be able to!) get rid of that by checking this branch out and updating that reference so it's referring to the same sha as in master.  Ping if issues. :-)

**Comment by lazd** [comment]
@camjc does this relate to the JP problem you noted?

**Comment by jzohrab** [comment]
fyi @shaperilio and anyone else -- I've pulled parts of this over to Li in (wip) PR https://github.com/covidatlas/li/pull/193, and implemented it for JP.  @shaperilio I reused your work for that, thanks.  We still have to implement the paging for all the scrapers that Emilio did in this PR, so I'm leaving this open until I create another issue in Li.

**Comment by jzohrab** [comment]
New issue in Li https://github.com/covidatlas/li/issues/350 covers the work in this PR, so I'm closing this one here.  Thank you very much @shaperilio ! z

**Pull request closed without merging**
