### PR TITLE
update: MO using arcgis + includes deaths

### PR DESCRIPTION
**Pull request by cmcjacob**

### CODE REVIEW

**Comment by lazd** [comment]
Seeing some weird behavior:

```
yarn timeseries -d 2020-3-21 -e 2020-3-21 -l "MO, USA"
yarn run v1.22.0
$ node src/shared/timeseries.js -d 2020-3-21 -e 2020-3-21 -l 'MO, USA'
⏳ Fetching scrapers...
✅ Fetched 132 scrapers!
✅ All scrapers are valid!
  ⚡️ Cache hit for https://health.mo.gov/living/healthcondiseases/communicable/novel-coronavirus/results.php from coronadatascraper-cache/2020-3-21/1c897b9a16d153c3dbf4e8acdf32b142.html
⏳ Calculating ratings...
✅ Assigned ratings for 1 sources
⏳ De-duping locations...
✅ De-duped 0 locations and found 0 crosscheck failures! 
✅ Data scraped!
   - 0 cities
   - 1 states
   - 123 counties
   - 0 countries
ℹ️  Total counts (tracked cases, may contain duplicates):
   - 180 cases
   - 0 tested
   - 0 recovered
   - 180 deaths
   - 0 active
⏳ Generating features...
  ❌ Could not find location St. Louis City County, MO, USA
  ⚠️  Skipping (unassigned), MO, USA because it's unassigned
  ❌ Could not find location Under 20 County, MO, USA
  ❌ Could not find location 20-29 County, MO, USA
  ❌ Could not find location 30-39 County, MO, USA
  ❌ Could not find location 40-49 County, MO, USA
  ❌ Could not find location 50-59 County, MO, USA
  ❌ Could not find location 60-69 County, MO, USA
  ❌ Could not find location 70+ County, MO, USA
```

and

```
yarn timeseries -d 2020-3-29 -e 2020-3-29 -l "MO, USA"
yarn run v1.22.0
$ node src/shared/timeseries.js -d 2020-3-29 -e 2020-3-29 -l 'MO, USA'
⏳ Fetching scrapers...
✅ Fetched 132 scrapers!
✅ All scrapers are valid!
https://maps.arcgis.com/sharing/rest/content/items/6f2a47a25872470a815bcd95f52c2872?f=json
  ⚠️ Cannot go back in time to get https://maps.arcgis.com/sharing/rest/content/items/6f2a47a25872470a815bcd95f52c2872?f=json, no cache present
  ❌ Error processing MO, USA:  TypeError: Cannot destructure property 'orgId' of 'dashboardManifest' as it is null.
    at Proxy.getArcGISCSVURL (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/lib/fetch/index.js:251:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.2020-3-29 (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/scrapers/USA/MO/index.js:257:18)
    at async runScrapers (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/events/crawler/scrape-data/run-scraper.js:103:38)
    at async generate (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/index.js:32:18)
    at async generateTimeseries (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/timeseries.js:193:18)
⏳ Calculating ratings...
✅ Assigned ratings for 0 sources
⏳ De-duping locations...
✅ De-duped 0 locations and found 0 crosscheck failures! 
✅ Data scraped!
   - 0 cities
   - 0 states
   - 0 counties
   - 0 countries
ℹ️  Total counts (tracked cases, may contain duplicates):
   - 0 cases
   - 0 tested
   - 0 recovered
   - 0 deaths
   - 0 active
❌ 1 error
⏳ Generating features...
✅ Found features for 0 out of 0 regions for a total of 0 features
```

**Comment by cmcjacob** [comment]
Looking into it

**Comment by cmcjacob** [comment]
Does 21659e0 address the issues?

**Comment by lazd** [comment]
Yup! Just had to change the last scraper to start on the 30th and it worked.

**Pull request merged**
