### PR TITLE
Fix scraping of JHU 'recovered' data

### LINKED ISSUE #618: Data obtained from JHU missing 'recovered' since 2020-03-24
As the subject goes.

On 2020-03-24 a new format of data was introduced which moved data about 'recovered' to a separate file. The applicable code does not handle this properly.

### PR DESCRIPTION
**Pull request by yoctozepto**
Note the 'US' conditional branch is never hit there because of
the lack of US states in the global data (separate issue).

Closes #618

### CODE REVIEW

**Comment by lazd** [comment]
The US branch will get hit for old data, but this fix looks good. Will give it a test and merge

**Comment by yoctozepto** [comment]
@lazd I beg to differ, this is already variant for the new data so it will not get hit.

**Comment by lazd** [comment]
@yoctozepto ah, so there is still a useless branch? Does it seem to be affecting anything?

**Comment by lazd** [comment]
Yup, you're totally right about that, and this fix works great. Thanks!

**Pull request merged**
