### PR TITLE
Fix Maine scraper

### PR DESCRIPTION
**Pull request by kb1ujs**

### CODE REVIEW

**Comment by lazd** [comment]
The ME scraper seems to work fine. What issue are you trying to solve? There is no description on this PR.

**Comment by lazd** [comment]
```
lazd@covidatlas:~/coronadatascraper$ yarn start -d 2020-4-3 -l "ME, USA"
yarn run v1.22.4
$ node src/shared/cli/index.js -d 2020-4-3 -l 'ME, USA'
⏳ Fetching scrapers...
✅ Fetched 135 scrapers!
✅ All scrapers are valid!
  ⚡️ Cache hit for https://www.maine.gov/dhhs/mecdc/infectious-disease/epi/airborne/coronavirus.shtml from coronadatascraper-cache/2020-4-3/fb7fe04355fea011b83c02cb859ed43a.html
⏳ Calculating ratings...
✅ Assigned ratings for 1 sources
⏳ De-duping locations...
✅ De-duped 0 locations and found 0 crosscheck failures! 
✅ Data scraped!
   - 0 cities
   - 1 states
   - 17 counties
   - 0 countries
ℹ️  Total counts (tracked cases, may contain duplicates):
   - 864 cases
   - 0 tested
   - 226 recovered
   - 150 deaths
   - 488 active
⏳ Generating features...
  ℹ️  Skipping (unassigned), iso2:US-ME, iso1:US because it's unassigned
✅ Found features for 17 out of 18 regions for a total of 17 features
⏳ Getting population data...
  ❌ (unassigned), iso2:US-ME, iso1:US: ?
✅ Found population data for 17 out of 18 locations
⏳ Transforming IDs...
✅ Transformed IDs for 17 out of 18 locations
⏳ Validating and cleaning locations...
✅ All locations are valid!
✏️  dist/data-2020-4-3.json written
✏️  dist/data-2020-4-3.csv written
✏️  dist/features-2020-4-3.json written
✏️  dist/report.json written
✏️  dist/ratings.json written
✏️  dist/reports/crawler-report.csv written
Done in 2.86s.
lazd@covidatlas:~/coronadatascraper$ yarn start -d 2020-4-2 -l "ME, USA"
yarn run v1.22.4
$ node src/shared/cli/index.js -d 2020-4-2 -l 'ME, USA'
⏳ Fetching scrapers...
✅ Fetched 135 scrapers!
✅ All scrapers are valid!
  ⚡️ Cache hit for https://www.maine.gov/dhhs/mecdc/infectious-disease/epi/airborne/coronavirus.shtml from coronadatascraper-cache/2020-4-2/fb7fe04355fea011b83c02cb859ed43a.html
⏳ Calculating ratings...
✅ Assigned ratings for 1 sources
⏳ De-duping locations...
✅ De-duped 0 locations and found 0 crosscheck failures! 
✅ Data scraped!
   - 0 cities
   - 1 states
   - 17 counties
   - 0 countries
ℹ️  Total counts (tracked cases, may contain duplicates):
   - 752 cases
   - 0 tested
   - 188 recovered
   - 136 deaths
   - 428 active
⏳ Generating features...
  ℹ️  Skipping (unassigned), iso2:US-ME, iso1:US because it's unassigned
✅ Found features for 17 out of 18 regions for a total of 17 features
⏳ Getting population data...
  ❌ (unassigned), iso2:US-ME, iso1:US: ?
✅ Found population data for 17 out of 18 locations
⏳ Transforming IDs...
✅ Transformed IDs for 17 out of 18 locations
⏳ Validating and cleaning locations...
✅ All locations are valid!
✏️  dist/data-2020-4-2.json written
✏️  dist/data-2020-4-2.csv written
✏️  dist/features-2020-4-2.json written
✏️  dist/report.json written
✏️  dist/ratings.json written
✏️  dist/reports/crawler-report.csv written
Done in 2.81s.
lazd@covidatlas:~/coronadatascraper$ 
```

**Comment by kb1ujs** [comment]
The format of the web site being scraped changed.  An additional row was added to the table being scraped for the county information on April 2.  Because of that, the data being pulled in for deaths is incorrect.  Refer to issue 631.

**Comment by lazd** [comment]
Can you resolve the conflicts? I was unable to get this in for tonight's release, but I will tomorrow if you can get it fixed up!

**Comment by kb1ujs** [comment]
I believe I have taken care of the conflicts.  Don't know why lint is still failing.  I made the changes specified.

**Comment by lazd** [comment]
Thanks!

**Pull request merged**
