### PR TITLE
Wrote a parser for the new US/NV Quad-County case data source. #861

### PR DESCRIPTION
**Pull request by appastair**
## Summary

Wrote a parser for US/NV Quad-County #861 

## Changes

Using new data source.

### CODE REVIEW

**Comment by appastair** [comment]
Thanks, @jzohrab! :raised_hands:

**Comment by jzohrab** [comment]
Reviewing this PR now, thanks @appastair.

**Comment by jzohrab** [comment]
I haven't tried this code out yet, but it looks great!

I see you deleted the old washoe county, so I verified that this PR and master return the same data at the old dates in the scraper:

```
Master scrapes:

yarn start --location US/NV/washoe-county.js
doesn't work ...

yarn start --location US/NV/washoe-county.js --date 2020-03-27
{ cases: 75, deaths: 0, recovered: 5, active: 70 }

yarn start --location US/NV/washoe-county.js --date 2020-04-06
{ cases: 281, deaths: 4, recovered: 30, active: 247 }
```

Great stuff!

**Comment by jzohrab** [comment]
Testing carson city.  One issue found: the page appears to load in the final data with some fancy ajax or similar calls, so the data isn't actually fully present if you do a `fetch.page`.  I changed this to `fetch.headless` and it worked fine, getting all the data:

```
[
  {
    county: 'Carson City',
    cases: 48,
    active: 19,
    recovered: 28,
    deaths: 1
  },
 ...
]
```

I'll do some other things in a separate branch, building off of what you've done to get your work in. :-)  cheers!

**Comment by jzohrab** [comment]
Closing, have made minor updates and pushed branch, merging in PR https://github.com/covidatlas/coronadatascraper/pull/964.

Great work, thank you!

**Pull request closed without merging**
