### PR TITLE
Scraper tests by date

### PR DESCRIPTION
**Pull request by HerbCaudill**
- Organizes test assets into folders by date
- Changes `scrapers.all.test.js` accordingly
- Updates docs accordingly
- Adds some generated test assets

### CODE REVIEW

**Comment by HerbCaudill** [comment]
Just noticed #481, which I guess renders all of this moot anyway?

**Comment by jzohrab** [comment]
@HerbCaudill This PR is still necessary, the move to tape in #481 only changes the framework.  The test files all moved to `tests`.

**Comment by jzohrab** [comment]
Related to https://github.com/covidatlas/coronadatascraper/issues/450.  @HerbCaudill , LMK if you need a hand getting this one done.  I think it will be more necessary as we start to do caching by date.

**Comment by jzohrab** [comment]
Closing, have reworked this with the latest code changes, moved files as needed, etc.  First PR issued for data (https://github.com/covidatlas/coronadatascraper/pull/632) and will issue another for code changes next.  Thanks Herb!

**Pull request closed without merging**
