### PR TITLE
Graph

### PR DESCRIPTION
**Pull request by webguyty**
## Summary

Basic graph in early stages showing an overview of all the dates displaying data in linear or logarithmic function. 

Bar chart showing daily cases or deaths. UI for development.

Have not styled yet.

### CODE REVIEW

**Comment by jzohrab** [comment]
Pinged @webguyty on Slack, so we can either finish this or close it.  Cheers all! z

**Comment by webguyty** [comment]
Working graphs which show overview of total data and also daily reported graph. 
Can view linear or logarithmic display.

Legend which has data that can be toggled on and off to change graph.

Tool tips on data points.

Will continue to work on styling, UI, get tool tips to display better.

**Comment by jzohrab** [comment]
Pinged @webguyty on Slack.  I can fix the cache conflict, if this work is good to go let me know and I'll fix it, merge it, and close this PR.  Cheers, jz

fyi @lazd

**Comment by jzohrab** [comment]
Closed, thanks!

**Pull request closed without merging**
