### PR TITLE
RFC: Add tesseract and kern county scraper

### PR DESCRIPTION
**Pull request by livejake**
Need to suppress the error messages and know that eng.traineddata isn't in an ideal place, but just pushing it up for comments.

### CODE REVIEW

**Comment by hyperknot** [comment]
How big is the whole tesseract package + the OCR model for it?

**Comment by livejake** [comment]
TesseractJS is 1.1 MB, the model eng.traineddata is 23.1 mb

**Comment by hyperknot** [comment]
Also affected here: https://github.com/lazd/coronadatascraper/issues/489

**Comment by livejake** [comment]
Could maybe use something like https://github.com/shelfio/aws-lambda-tesseract to get size down to 6 mb

**Comment by camjc** [comment]
Do we really want to head down the path of OCR?
Seems like data reliability would massively decrease if we use OCR? CC @lazd @ryanblock

**Comment by livejake** [comment]
If OCR is the only option, then I think it can be a valuable resource. However, given its reliability issues, we should require additional testing. For example, in this PR, I test for internal consistency. I could also look at if text strings changed or some other attributes.

**Comment by jzohrab** [comment]
Hi @livejake , are you continuing work on this PR's branch?  Cheers! jz

**Comment by lazd** [comment]
TBH, I don't think scraping images is really within scope. I'd rather find a person in a given state to curate a data source for us until the state/county figures out how to internet. In this case, Harriet Rowan curates CA for us daily and does a fantastic job. Though this is definitely a magnificent application of the technology and it's impressive that it's been made to work, it's not sustainable and would be potentially quite brittle (like our scrapers aren't already, heh).

So I say we close this, but tip our hats to @livejake for attempting to work with the absolute boneheads at the Kern County Public Health Services Department ❤️

**Comment by livejake** [comment]
Ok. I understand your perspective. If you ever change your mind, happy to help finalize.

**Pull request closed without merging**
