### PR TITLE
Fix: Louisiana, USA counties -> parishes

### PR DESCRIPTION
**Pull request by praging**
Removes inconsistencies among Louisiana Parish names.

Fixes https://github.com/covidatlas/coronadatascraper/issues/549.

Note: issues opened re: timeseries errors in Louisiana, which are unrelated to this fix -- see https://github.com/covidatlas/coronadatascraper/issues/553, https://github.com/covidatlas/coronadatascraper/issues/552

### CODE REVIEW

**Comment by lazd** [comment]
TBH this `Parish`/`County` thing is so annoying, this is like the 3rd time we've had to fix it, I'm just merging this and hoping you did it right.

THANK YOU!

**Comment by lazd** [comment]
lol this broke every other county in the entire US

**Comment by caticoa3** [comment]
😅

**Comment by praging** [comment]
LOL

**Comment by lazd** [comment]
It's all good, it was a 2 second fix and I got a chuckle out it.

**Pull request merged**
