### PR TITLE
fix: VA, USA (counties -> cities)

### PR DESCRIPTION
**Pull request by praging**
all population errors resolved; 38 cities renamed from county; minor caps fix.

### CODE REVIEW

**Comment by lazd** [comment]
Ok this is awesome, but it does break the timeseries for 3/25 because the county names are different:

```
 yarn timeseries -l "VA, USA" -d 2020-3-25 -e 2020-3-25
```

Returns

```
  ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Buena Vista City, no cache present
  ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Fairfax City, no cache present
  ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Franklin City, no cache present
  ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Lynchburg, no cache present
  ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Manassas City, no cache present
  ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Richmond City, no cache present
  ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Roanoke City, no cache present
```

We will have to have a special case for those

**Comment by lazd** [comment]
Yeah I tried to take a look at this, but there is a lot to untangle. Can you go back and make it work for 2020-3-25?

**Comment by chunder** [comment]
@aed3 Are you able to review this change? I think you did a lot of work on VA's county/city names too right?

**Comment by aed3** [comment]
> Ok this is awesome, but it does break the timeseries for 3/25 because the county names are different:
> 
> ```
>  yarn timeseries -l "VA, USA" -d 2020-3-25 -e 2020-3-25
> ```
> 
> Returns
> 
> ```
>   ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Buena Vista City, no cache present
>   ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Fairfax City, no cache present
>   ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Franklin City, no cache present
>   ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Lynchburg, no cache present
>   ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Manassas City, no cache present
>   ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Richmond City, no cache present
>   ⚠️ Cannot go back in time to get https://public.tableau.com/views/VirginiaCOVID-19Dashboard/VirginiaCOVID-19Dashboard.pdf?:showVizHome=no&Locality=Roanoke City, no cache present
> ```
> 
> We will have to have a special case for those

Those are the cities which were initially wrong, so there is no data for them the first day Virginia was being scraped. The fix would be to no check for them on that day,

**Comment by lazd** [comment]
Ok great, merging! Thanks for the review @aed3 !

**Pull request merged**
