### PR TITLE
Fix NL when data not available.

### PR DESCRIPTION
**Pull request by jzohrab**
If data is not available, old code returned empty array, which then caused
validation error 'iso1:NL: Error: Invalid data: scraper for iso1:NL returned 0 rows'.
Returning undefined follows our convention for 'empty' data, and doesn't
raise an error.

I'm not 100% sure this is the right thing to do, but it at least stops the error being thrown.

### CODE REVIEW

**Comment by lazd** [comment]
I'd rather return data from yesterday than nothing... Can we do that, like the rest of the timeseries scrapers (NYT, etc)?

**Comment by jzohrab** [comment]
I didn't see this comment!  I just submitted a PR that changes NYT to return 'undefined' if we don't have data. :-)

I feel we _shouldn't_ return data from yesterday, that feels like an adjustment we can make during reporting/front-end.  We should sort that out, that's a big difference, but I think it's the right thing to do (to differentiate between real data we actually have vs inferences we're making).

**Comment by jzohrab** [comment]
Yes, thinking more on this, I def. feel this is not the right thing to do.  It's easy to write checks that deal with data that we know is real, vs data that we're making up.

**Comment by jzohrab** [comment]
Updated so that NL returns yesterday's data when today's isn't ready.  That seems ok to me, given how flexible time is, and it's not terrible to report yesterday's.  One potential issue: if the source goes stale, we'll always report the same thing ... but that's a common problem anyway.  Cheers @lazd , merging this one, it seems OK to me and passes locally.

**Pull request merged**
